### ISSUE TITLE
Website not loading correctly 

### ISSUE THREAD

**Issue by Kyvrixon** [IgorKowalczyk/majobot#1045]
### Environment

Windows 11 Home 23H2 Build 22631.3880

### Steps To Reproduce

1. start bot (when everything works properly)
2. run any slash command

### Software Version

latest from repo

### Expected Behavior

slash command to work

### Actual Behavior

Slash command is deferred but not replied to. Console errors

### Severity

Critical

### Priority

High

### Type

Functional, Usability

### Additional Information

I think this might be with the prisma schema but not sure, nothing appears in monogDB (as in no models). Could be on my side too?
```
@majoexe/bot:deploy: error - PrismaClientKnownRequestError:
@majoexe/bot:deploy: Invalid `prisma.guild.upsert()` invocation:
@majoexe/bot:deploy:
@majoexe/bot:deploy:
@majoexe/bot:deploy: Inconsistent column data: Malformed ObjectID: provided hex string representation must be exactly 12 bytes, instead got: "clyp0w0na0000h2iwml9wvz32", length 25 for the field 'id'.
```
This still exists despite the modals, fonts, events and commands loading and registering properly. What do you think the issue is here? *Note: the dashboard site loads properly for a split second then turns into a mess (see https://github.com/IgorKowalczyk/majo.exe/issues/1041#issuecomment-2230668747 for console log screenshots in devtools)*
```
@majoexe/dashboard:deploy: [next-auth][error][CLIENT_FETCH_ERROR]
@majoexe/dashboard:deploy: https://next-auth.js.org/errors#client_fetch_error fetch failed {
@majoexe/dashboard:deploy:   error: {
@majoexe/dashboard:deploy:     message: 'fetch failed',
@majoexe/dashboard:deploy:  ✓ Generating static pages (28/28)
@majoexe/dashboard:deploy:     stack: 'TypeError: fetch failed\n' +
@majoexe/dashboard:deploy:       '    at node:internal/deps/undici/undici:12502:13\n' +
@majoexe/dashboard:deploy:       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
@majoexe/dashboard:deploy:     name: 'TypeError'
@majoexe/dashboard:deploy:   },
@majoexe/dashboard:deploy:   url: 'http://localhost/api/auth/providers',
@majoexe/dashboard:deploy:   message: 'fetch failed'
@majoexe/dashboard:deploy: }
@majoexe/dashboard:deploy: [next-auth][error][CLIENT_FETCH_ERROR]
@majoexe/dashboard:deploy: https://next-auth.js.org/errors#client_fetch_error fetch failed {
@majoexe/dashboard:deploy:   error: {
@majoexe/dashboard:deploy:     message: 'fetch failed',
@majoexe/dashboard:deploy:     stack: 'TypeError: fetch failed\n' +
@majoexe/dashboard:deploy:       '    at node:internal/deps/undici/undici:12502:13\n' +
@majoexe/dashboard:deploy:       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
@majoexe/dashboard:deploy:     name: 'TypeError'
@majoexe/dashboard:deploy:   },
@majoexe/dashboard:deploy:   url: 'http://localhost/api/auth/providers',
@majoexe/dashboard:deploy:   message: 'fetch failed'
@majoexe/dashboard:deploy: }
```

**Comment by IgorKowalczyk** [comment]
Show your prisma scheme, you might have done something incorrectly.

Prisma doesn't support mongoDB out of the box, you have to adjust the schema as in the documentation: https://www.prisma.io/docs/orm/overview/databases/mongodb

As for the next.js console - these errors you can expect, it is just normal. In the short term I will start working on updating [next-auth](https://next-auth.js.org/) to [authjs](https://authjs.dev/)

**Comment by IgorKowalczyk** [comment]
You can try running `pnpm run deploy --filter=dashboard`. If everything compiles correctly you should see the bot's dashboard, if you don't see it try clearing cache and local storage
