### ISSUE TITLE
Cannot run bot

### ISSUE THREAD

**Issue by Dominiqos** [IgorKowalczyk/majobot#19]
![Screenshot_2021-08-28-10-26-51-93](https://user-images.githubusercontent.com/82405746/131211863-81894df4-b29a-42c0-9313-e4bb2ce4a8b8.jpg)

**Comment by r-kjha** [comment]
The bot is coded on nodejs 14.x but replit only has 12.x. There is a work around but that way too tidious.

**Comment by IgorKowalczyk** [comment]
> The bot is coded on nodejs 14.x but replit only has 12.x. There is a work around but that way too tidious.

I found solution. Run these commands in the replit terminal
```
npm init -y && npm i --save-dev node@14 && npm config set prefix=$(pwd)/node_modules/node && export PATH=$(pwd)/node_modules/node/bin:$PATH

npm ci
```

**Comment by kittylegitcheck2** [comment]
It works thank you!

**Comment by kittylegitcheck2** [comment]
But i have one more thing, sorry i am dumb.

**Comment by kittylegitcheck2** [comment]
I setup the dashboard to be true, added everything with the star mark and added all the redirects in developer portal. I do not know why te website does not work, because i own the domain. Is there like a spot for editing DNS?

**Comment by IgorKowalczyk** [comment]
> Is there like a spot for editing DNS? Or does the port have to be something else than 80

Can you explain this more? What does "not working" mean, nothing shows up, you see a 502 error or something else?

**Comment by kittylegitcheck2** [comment]
![Uploading Screenshot_2021-08-28-21-50-07-73.jpg…]()

**Comment by kittylegitcheck2** [comment]
#
![Screenshot_2021-08-28-21-50-07-73](https://user-images.githubusercontent.com/82405746/131229444-d6f9b9f7-6ea3-4580-98e6-d2cfea16b77f.jpg)

**Comment by IgorKowalczyk** [comment]
Hmm, so check the domain & ngnix config. Ngnix should point to your domain

**Comment by kittylegitcheck2** [comment]
That is awkward, because i have no kdea what is nginx or ngnix. This is the first time i am doing something with a domain...

**Comment by IgorKowalczyk** [comment]
You need to create a reverse proxy with nginx from localhost or VPS IP to the domain

**Comment by Dominiqos** [comment]
But how do i do that? Because i have no idea. Sorry if i am like a very annoying person but i never worked with domains.

**Comment by IgorKowalczyk** [comment]
You are not an annoying person. I understand that you have problems, I used to have them myself ;-;
I can't give you examples here, etc but I'll try to describe it
 - `DOMAIN` should be set to `https://your.domain.address` but you can try `https://localhost`. Try changing the `localhost: true` value in `config.js`
 - `PORT` should be set to `80`/`8080` but you can set other values as well (you have to see that the port is not blocked)
 - Nginx should point to your localhost site and should also be set to output to your domain.
 
You can check out reverse proxy tutorials on the internet. In my case it worked

**Comment by Dominiqos** [comment]
Do tou have discord? Because i would like to contact you and add you to my replit project, because if i am honest i have no idea what i am doing. Also if replit will not work for the bot i can ude heroku. Or if it is easier i can use heroku. But i will have to wait 2 more days to get more free hours.

**Comment by IgorKowalczyk** [comment]
Yes, I have a Discord - `Majonez.exe#3957`. You can add me. For me, the replit option will be more comfortable. Majo has support for replit after the latest changes.
I am also closing this issue. After we solve the problems I will write here how to fix them. 😁
